import type { FaqSection } from "./types";

export const sectionD: FaqSection = {
  id: "faq-ai-quality",
  title: "D. AI, Content Quality & Accuracy",
  intro: "How content is generated, accuracy, difficulty, plagiarism and why outputs can vary.",
  items: [
    {
      question: "How does Studiely generate its study content?",
      schemaText:
        "Studiely uses advanced AI language models guided by a curriculum-specific framework developed by the Studiely team. When a student selects their curriculum, exam board, grade level, subject and topic, this full academic context shapes the AI's output from the ground up — it is not a post-generation filter applied to generic content. All content generated by Studiely is original and unique to each request. The platform's curriculum guidelines are updated as specifications evolve and output quality is reviewed continuously against official syllabus materials.",
      answer: (
        <>
          <p>
            Studiely uses advanced AI language models guided by a curriculum-specific framework developed by the
            Studiely team. When a student selects their curriculum, exam board, grade level, subject and topic, this
            full academic context shapes the AI&apos;s output from the ground up — it is not a post-generation filter
            applied to generic content.
          </p>
          <p>
            This curriculum-first approach is what separates Studiely from simply using a general AI tool for
            revision. A general AI tool may produce accurate subject knowledge, but it is not calibrated to the
            scope, depth, terminology, or assessment expectations of the student&apos;s specific route.
          </p>
          <p>
            All content generated by Studiely is original and unique to each request. The platform&apos;s curriculum
            guidelines are updated as specifications evolve and output quality is reviewed continuously against
            official syllabus materials.
          </p>
        </>
      ),
    },
    {
      question: "Is Studiely's content accurate and reliable?",
      schemaText:
        "Studiely's content is designed to be curriculum-aligned, educationally sound and exam-relevant. The platform's AI operates within curriculum-specific rules that significantly reduce the risk of off-syllabus or factually incorrect content. Like all AI-generated content, Studiely's outputs should be used as a study aid alongside — not as a replacement for — official course materials. Students are encouraged to cross-reference important concepts with their school's official materials, consult their teacher if generated content does not match what they have been taught and use past exam papers from their exam board's official website alongside Studiely for final preparation.",
      answer: (
        <>
          <p>
            Studiely&apos;s content is designed to be curriculum-aligned, educationally sound and exam-relevant. The
            platform&apos;s AI operates within curriculum-specific rules that significantly reduce the risk of
            off-syllabus or factually incorrect content.
          </p>
          <p>
            That said, like all AI-generated content, Studiely&apos;s outputs should be used as a study aid alongside
            — not as a replacement for — official course materials. Students are encouraged to:
          </p>
          <ul>
            <li>Cross-reference important concepts with their school&apos;s official materials</li>
            <li>Consult their teacher if generated content does not match what they have been taught</li>
            <li>
              Use past exam papers from their exam board&apos;s official website alongside Studiely for final
              preparation
            </li>
          </ul>
          <p>
            If an output is unclear or appears to need refinement, students can regenerate it at any time or ask Nyla
            to clarify specific points.
          </p>
        </>
      ),
    },
    {
      question: "Can I control the difficulty level of generated content?",
      schemaText:
        "Yes. Before generating content, students can select a difficulty level: beginner, intermediate, or advanced. This setting affects the depth, complexity and challenge level of the output across all study tools. Beginner is useful when approaching a topic for the first time or building foundational understanding. Intermediate reflects standard exam expectations for the chosen curriculum. Advanced is suited for students targeting top grades who want to engage with greater depth. The difficulty setting works alongside curriculum and grade level selection.",
      answer: (
        <>
          <p>
            Yes. Before generating content, students can select a difficulty level: beginner, intermediate, or
            advanced.
          </p>
          <p>
            This setting affects the depth, complexity and challenge level of the output across all study tools.
            Beginner is useful when approaching a topic for the first time or building foundational understanding.
            Intermediate reflects standard exam expectations for the chosen curriculum. Advanced is suited for
            students targeting top grades who want to engage with greater depth.
          </p>
          <p>
            The difficulty setting works alongside curriculum and grade level selection, so the platform calibrates
            output around both the student&apos;s academic route and their current study stage.
          </p>
        </>
      ),
    },
    {
      question: "Is Studiely's content plagiarism-free?",
      schemaText:
        "Yes. Every piece of content generated by Studiely is created uniquely for that specific request at the moment it is made. The platform does not pull pre-written content from a database or reproduce existing published materials. Students can use Studiely's generated notes, flashcards and worked examples as personal study materials without plagiarism concerns. Studiely is designed as a revision and study aid, not a content submission tool.",
      answer: (
        <>
          <p>
            Yes. Every piece of content generated by Studiely is created uniquely for that specific request at the
            moment it is made. The platform does not pull pre-written content from a database or reproduce existing
            published materials.
          </p>
          <p>
            This means students can use Studiely&apos;s generated notes, flashcards and worked examples as personal
            study materials without plagiarism concerns — every output is original, even when multiple students
            request content on the same topic.
          </p>
          <p>
            Studiely is designed as a revision and study aid, not a content submission tool. Its purpose is to help
            students understand and practise their subject — not to produce content for handing in as coursework or
            assignments.
          </p>
        </>
      ),
    },
    {
      question: "Why does the generated output sometimes vary between requests?",
      schemaText:
        "AI models generate responses probabilistically rather than retrieving fixed answers. Two requests for notes on the same topic may produce slightly different outputs in terms of structure, phrasing, or emphasis — even with identical settings. In revision contexts, this is often useful. If you find a particular output especially useful, save or export it before regenerating. Premium users can export content to PDF or Word for permanent offline access.",
      answer: (
        <>
          <p>
            AI models generate responses probabilistically rather than retrieving fixed answers. Two requests for
            notes on the same topic may produce slightly different outputs in terms of structure, phrasing, or
            emphasis — even with identical settings.
          </p>
          <p>
            In revision contexts, this is often useful. When a student regenerates content on a difficult topic, they
            may get a different angle or framing that helps them understand something the first version did not fully
            clarify.
          </p>
          <p>
            If you find a particular output especially useful, save or export it before regenerating. Premium users
            can export content to PDF or Word for permanent offline access.
          </p>
        </>
      ),
    },
  ],
};
