export const CUR_DATA: Record<string, Record<string, string[]>> = {
  "British Curriculum": {
    "UK National Curriculum": [
      "Nursery (Pre-K)",
      "Reception (KG)",
      "Year 1 (KS1)",
      "Year 2 (KS1)",
      "Year 3 (KS2)",
      "Year 4 (KS2)",
      "Year 5 (KS2)",
      "Year 6 (KS2)",
      "Year 7 (KS3)",
      "Year 8 (KS3)",
      "Year 9 (KS3)",
      "GCSE (KS4)",
      "AS Level (KS5)",
      "A Level (KS5)",
    ],
    "Cambridge International": [
      "Nursery",
      "Reception",
      "Year 1",
      "Year 2",
      "Year 3",
      "Year 4",
      "Year 5",
      "Year 6 (Primary)",
      "Primary Checkpoint",
      "Year 7",
      "Year 8",
      "Year 9 (Lower Secondary)",
      "Lower Secondary Checkpoint",
      "IGCSE",
      "AS Level",
      "A Level",
    ],
    "Pearson Edexcel": [
      "Nursery (EYFS)",
      "Reception (EYFS)",
      "Year 1",
      "Year 2",
      "Year 3",
      "Year 4",
      "Year 5",
      "Year 6",
      "Year 7",
      "Year 8",
      "Year 9",
      "GCSE",
      "AS Level",
      "A Level",
    ],
  },
  "US Curriculum": {
    "US Standards": [
      "Kindergarten",
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
      "Grade 10",
      "Grade 11",
      "Grade 12",
    ],
    "AP Pathway": [
      "Grade 9 (AP Eligible)",
      "Grade 10 (AP Eligible)",
      "Grade 11 — AP",
      "Grade 12 — AP",
    ],
  },
  "IB": {
    PYP: ["Grade 1 (PYP)", "Grade 2 (PYP)", "Grade 3 (PYP)", "Grade 4 (PYP)", "Grade 5 (PYP)"],
    MYP: ["Grade 6 (MYP)", "Grade 7 (MYP)", "Grade 8 (MYP)", "Grade 9 (MYP)", "Grade 10 (MYP)"],
    DP: ["Grade 11 — DP1", "Grade 12 — DP2"],
  },
  "Australian Curriculum": {
    "Any State": [
      "Foundation",
      "Year 1",
      "Year 2",
      "Year 3",
      "Year 4",
      "Year 5",
      "Year 6",
      "Year 7",
      "Year 8",
      "Year 9",
      "Year 10",
    ],
    "NSW → HSC": ["Year 11 (HSC)", "Year 12 (HSC)"],
    "VIC → VCE": ["Year 11 (VCE)", "Year 12 (VCE)"],
  },
  "Canadian Curriculum": {
    "Any Province": [
      "Kindergarten",
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
      "Grade 10",
    ],
    "Ontario → OSSD": ["Grade 11 (OSSD)", "Grade 12 (OSSD)"],
    "BC → BC Grad": ["Grade 11 (BC)", "Grade 12 (BC)"],
  },
};

export const REVIEWS_1 = [
  {
    quote:
      "I picked Cambridge IGCSE Biology, typed 'Photosynthesis', and had full notes and a quiz in under a minute. Absolute game changer.",
    name: "Aisha K.",
    role: "IGCSE Student",
    initials: "AK",
    col: "var(--color-teal)",
  },
  {
    quote:
      "The exam question generator is perfectly matched to A-Level format. My grades went up a full grade boundary after two weeks.",
    name: "James T.",
    role: "A-Level Student",
    initials: "JT",
    col: "var(--color-indigo)",
  },
  {
    quote:
      "I use the flashcard tool before every IB DP exam. It knows exactly what the syllabus covers. Best study app I've ever used.",
    name: "Maha",
    role: "IB Diploma Student",
    initials: "PS",
    col: "var(--color-amber)",
  },
  {
    quote:
      "Nyla explained every concept I didn't understand from my notes. It's like having a tutor available at 2am.",
    name: "Omar F.",
    role: "GCSE Student",
    initials: "OF",
    col: "var(--color-teal)",
  },
  {
    quote:
      "The writing practice mode is incredible. I practiced AP History essays with a timer. My teacher noticed improvement immediately.",
    name: "Sophie L.",
    role: "AP Student",
    initials: "SL",
    col: "var(--color-indigo)",
  },
  {
    quote:
      "Generated a full quiz on WW2 in 30 seconds. My whole friend group uses Studiely now.",
    name: "Yusuf A.",
    role: "Year 9 Student",
    initials: "YA",
    col: "var(--color-amber)",
  },
];

export const REVIEWS_2 = [
  {
    quote:
      "The notes are so well structured. It's like having a perfect revision guide written just for me and my exact exam board.",
    name: "Mei C.",
    role: "A-Level Student",
    initials: "MC",
    col: "var(--color-indigo)",
  },
  {
    quote:
      "Used it to prep for Cambridge entrance. The exam question generator for A-Level Maths is genuinely impressive.",
    name: "Daniel O.",
    role: "University Prep",
    initials: "DO",
    col: "var(--color-teal)",
  },
  {
    quote:
      "I was struggling with Chemistry. Studiely made flashcards from my topic and I finally understand reactions properly.",
    name: "Fatima R.",
    role: "IGCSE Student",
    initials: "FR",
    col: "var(--color-amber)",
  },
  {
    quote:
      "Nyla is the best part. I ask it questions and it knows I'm in MYP Grade 9. The answers are always relevant.",
    name: "Liam B.",
    role: "IB MYP Student",
    initials: "LB",
    col: "var(--color-teal)",
  },
  {
    quote:
      "Study time went from 3 hours to 45 minutes. The quiz tool tests me on exactly what I need to know.",
    name: "Zara H.",
    role: "Grade 10 Student",
    initials: "ZH",
    col: "var(--color-indigo)",
  },
  {
    quote:
      "The writing feedback references the mark scheme for my board. It actually tells me how to improve. Unreal.",
    name: "Arjun P.",
    role: "AS Level Student",
    initials: "AP",
    col: "var(--color-amber)",
  },
];

export const PRICING_PLANS = [
  {
    name: "Free",
    price: "$0",
    cad: "Forever free",
    feats: [
      "5 total generations",
      "Notes (5 only)",
      "Flashcards (5 only)",
      "Quizzes (5 only)",
      "Exam Qs (5 only)",
    ],
    miss: ["Export PDF / Word", "Offline Access", "Nyla Priority", "Analytics", "Study Streaks"],
    cta: "Get Started",
    fine: "After 5 gens, upgrade.",
  },
  {
    name: "Monthly",
    price: "$8.91",
    sub: "/mo",
    cad: "Billed monthly",
    badge: "67% OFF",
    orig: "Was $26.99/mo",
    feats: [
      "Unlimited all tools",
      "Export PDF & Word",
      "Offline Access",
      "Nyla Priority",
      "Learning Analytics",
      "Study Streaks",
    ],
    miss: [],
    cta: "Choose Monthly",
    fine: "Cancel anytime.",
  },
  {
    name: "3 Months",
    price: "$25.41",
    cad: "$8.47/mo · 3 months",
    badge: "67% OFF",
    orig: "Was $76.99",
    feats: [
      "Everything in Monthly",
      "Unlimited all tools",
      "Export PDF & Word",
      "Offline Access",
      "Nyla Priority",
      "Analytics",
    ],
    miss: [],
    cta: "Choose 3 Months",
    fine: "Cancel anytime.",
  },
  {
    name: "6 Months",
    price: "$49.50",
    cad: "$8.25/mo · 6 months",
    badge: "67% OFF",
    orig: "Was $149.99",
    feats: [
      "Everything in Monthly",
      "Unlimited all tools",
      "Export PDF & Word",
      "Offline Access",
      "Nyla Priority",
      "Analytics",
    ],
    miss: [],
    cta: "Choose 6 Months",
    fine: "Cancel anytime.",
  },
  {
    name: "Annual",
    price: "$89.10",
    sub: "/yr",
    cad: "Only $7.43/mo",
    badge: "🔥 Best Value",
    orig: "Was $269.99/yr",
    feats: [
      "Everything in Monthly",
      "Unlimited all tools",
      "Export PDF & Word",
      "Offline Access",
      "Nyla Priority",
      "Learning Analytics",
      "Study Streaks",
    ],
    miss: [],
    cta: "Choose Annual",
    fine: "67% launch offer. Cancel anytime.",
    featured: true,
  },
];
